baseURL: https://dhemasnurjaya.com/
title: Dhemas Nurjaya
subtitle: Software Engineer
languageCode: en-us
paginate: 5
theme: PaperMod

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
