main:
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 1
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 2
  - identifier: search
    name: Search
    url: /search/
    weight: 3
  # - identifier: example
  #   name: example.org
  #   url: https://example.org
  #   weight: 4