env: development

label:
  text: "#!"

keywords: [Blog, Portfolio, Software, Developer, Engineer, Code, Coding, Tech, Mobile, Android, iOS, Flutter, Dart]
author: Me
contact:
  email: dhemasnurjaya@gmail.com

ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true

profileMode:
  enabled: true # needs to be explicitly set
  title: "Dhemas Eka Rilian Nurjaya"
  subtitle: "Passionate Software Engineer"
  # imageUrl: "https://placehold.co/120"
  # imageWidth: 120
  # imageHeight: 120
  # imageTitle: "Portrait of Dhemas"
  # buttons:
  #   - name: Posts
  #     url: posts
  #   - name: Tags
  #     url: tags

socialIcons:
  - name: linkedin
    url: "https://www.linkedin.com/in/dhemas-nurjaya-030890bb"
  - name: github
    url: "https://github.com/dhemasnurjaya"
  - name: x
    url: "https://x.com/dhemaseka"
  - name: facebook
    url: "https://www.facebook.com/Dhemas"
  - name: email
    url: "mailto:dhemasnurjaya@gmail.com"